theme = "autumn"

[editor]
scrolloff=8
cursorline=true
true-color=true
color-modes=true
shell = ["zsh"]
bufferline = "always"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.indent-guides]
render = true
character = "‚ñè"
skip-levels = 1

[editor.lsp]
display-messages=true


[keys.normal]
C-v = "vsplit"
esc = ["collapse_selection" ,"keep_primary_selection", ":w"]
"C-." = "goto_next_buffer"
"C-," = "goto_previous_buffer"
"A-r" = [":config-reload", ":reload-all"]
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before"
]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before"
]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
[keys.insert]
"C-space" = "completion"
